contact/urls.py
from django.conf.urls import url,include

from .views import *

urlpatterns = [

    url(r'^contact/$', contactform, name='contact'),
    url(r'^thanks/$', thanks, name='thanks'),
    ]

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    sender = forms.EmailField(widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    copy = forms.BooleanField(required=False)

contact/views.py
from django.db import models
from django.http import BadHeaderError
from .forms import ContactForm
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import auth


def contactform(reguest):
    if reguest.method == 'POST':
        form = ContactForm(reguest.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            sender = form.cleaned_data['sender']
            message = form.cleaned_data['message']
            copy = form.cleaned_data['copy']
            recepients = ['lenbuh74@mail.ru']
            if copy:
                recepients.append(sender)
            try:
                send_mail(subject, message, 'lenbuh74@mail.ru', recepients)
            except BadHeaderError:
                return HttpResponse('Invalid header found')
            return redirect('http://127.0.0.1:8000/form/thanks')

    else:
        form = ContactForm()
    return render(reguest, "contact.html", {'form': form, 'username': auth.get_user(reguest).username})


def thanks(reguest):
    thanks = 'thanks'
    return render(reguest, 'thanks.html', {'thanks': thanks})

contact/templates/form/contact.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
{% block title %} - Обратная связь{% endblock %}

{% block contactform %}
 <div class="panel panel-success">
  <div class="panel-heading">
    <h2 class="panel-title">Обратная связь</h2>
  </div>
  <div class="panel-body">
<div class="well well-lg">
    <h3></h3>
<form action="{% url 'blog:contact' %}" method="post">
    {% csrf_token %}
{#    {% bootstrap_form form %}#}
    {{ form.non_field_errors }}
	<div>
	  <label for="id_subject">Тема:</label>
	  {{ form.subject.errors }}
{#	  {{ form.subject }}#}
      <input class="form-control" id="id_subject" name="subject" placeholder="Тема">
	</div>
    &nbsp;
	<div>
	  <label for="id_sender">E-mail:</label>
	  {{ form.sender.errors }}
{#	  {{ form.sender }}#}
      <input class="form-control" id="id_sender" name="sender" placeholder="Ваш e-mail">
	</div>
    &nbsp;
	<div>
	  <label for="id_message">Сообщение:</label>
	  {{ form.message.errors }}
{#	  {{ form.message }}#}
      <textarea class="form-control" id="id_message" name="message" placeholder="Введите ваше сообщение"></textarea>
	</div>
    &nbsp;
	<div>
	  {{ form.copy.errors }}
	  <label for="id_copy">{{ form.copy }} Отправить копию себе </label>
	</div>
    <br>
	<input type="submit" class="btn btn-success" value="Отправить сообщение"/>
</form>
  </div>
</div>
</div>

{% endblock %}

contact/templates/form/thanks.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
{% block contactform %}

 <div class="panel panel-success">
  <div class="panel-heading">
    <h2 class="panel-title"></h2>
  </div>
  <div class="panel-body">
<div class="well well-lg" align="center">
    <h3>Спасибо, Ваше сообщение отправлено!</h3>
    <div align="center"><a href="/"><button type="button" class="btn btn-info">Вернутся на главную</button></a></div>
  </div>
</div>
</div>
{% endblock %}